### ISSUE TITLE
 Intel PODM source code architecture and function flow 

### ISSUE THREAD

**Issue by lalithabheemavarapu** [intel/intelRSD#105]
Dear Intel,
Am going through the PODM code and in my review i thought of **RESTful service using spring and Hibernate. It comprises of DAO ,DTO and service layers w.r.to spring framework**.or RESTFul with JAX-RS.Is it right ?what exactly the function flow of PODM code .Can anybody please let me know.

Thanks in advance,
Lalitha

**Comment by lalithabheemavarapu** [comment]
Can anyone please help me on this.Please

**Comment by lalithabheemavarapu** [comment]
Can anyone working on IntelRSD PODM,Please response

**Comment by ArturBaryla** [comment]
Hi,
PODM 2.4 services use Spring Framework exclude NodeComposer service which use JAX-RS

Regards,
Artur Baryła

**Comment by lalithabheemavarapu** [comment]
Thanks Artur,Currently am working on V2.3.2 of Intel RSD PODM

**Comment by ArturBaryla** [comment]
PODM 2.3.2 uses JAX-RS and Hibernate (there is no Spring Framework)

**Comment by lalithabheemavarapu** [comment]
Thanks Artur for clarifying.
I have one more question ,while i going through code main() method is VaultDecrypterMain.java ,
How the PODM application will start execute next method or function after VaultDecrypterMain class.

i found  vault.json in /var/lib/pod-manager/vault/ in this path.How come vault.json is used 

Can i know how the PODM works after VaultDecrypterMain.java

Can you please answer ....

**Comment by ArturBaryla** [comment]
The main() method which you found in VaultDecrypterMain.java belongs to a tool program, not to Pod Manager application.
Here is the file where Pod Manager application starts:
PODM/SW/pod-manager/podm-rest/src/main/java/com/intel/podm/ApplicationStartup.java
To understand how Pod Manager code works you must be familiar with Java EE (Java Enterprise Edition) standard.

I suggest also reading Pod Manager User Guide for information about application deployment and usage. Here is the link:
https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/podm-user-guide-v2-3.html

**Comment by lalithabheemavarapu** [comment]
Thanks @ArturBaryla ....

**Comment by lalithabheemavarapu** [comment]
Hello Artur,

I have gone through podm-user guide and i have setup the podm application in my Ubuntu,and its running in Ubuntu.
when i observed  the podm-manager-application-log firstly it loading all the DB related podmclienr Resource Collections.
![pod-manager-log](https://user-images.githubusercontent.com/5384301/57609202-fe1c5e80-75a0-11e9-8a1c-f12b97603e4e.PNG)

PODM application context will initialize from  
web.xml	--> RequestValidationFilter --> FilterDispatcher ->init()
pod-manager from application module in wildfly app server .

How the  ApplicationStartup.java is been identified... ?

Can  you please answer...

**Comment by lalithabheemavarapu** [comment]
How the ApplicationStartup.java instantiated..

**Comment by karolrom-intel** [comment]
Dear Lalitha,
Just to confirm what is your end goal: are you looking for something specific or do you want to be able to read and understand Pod Manager code?

Quick answers to your questions:

Reference implementation of Pod Manager is written in Java EE and deployed on Wildfly.
Application initialization process is controlled by Wildfly and follows Java EE Specification, so there is no "main" method.

If you are looking for single starting place that will help you to walk through the major code areas, we recommend `ApplicationStartup` class. This class defines what needs to happen before we can safely say that application is started. Success of those steps is logged with “PodM started” message. Those steps are defined in `@DependsOn` annotation.
`ApplicationStartup` is a _EJB Singleton_, so instantiation process is controller by _EJB Container_.

If you do not have experience with Java EE, my recommendation is to start with Java EE tutorial/book first. It is not easy to understand how Java EE application works without this knowledge and you may be confused by lack of many parts like object instantiations or “`static void main()`” method.

**Comment by lalithabheemavarapu** [comment]
Thanks for Replying @karolrom-intel ,sure will go through the Java EE,just want to make sure of how the PODM  works and understand the POd Manager code ,as per our requirement will changing some code ,wanna make sure about the exact flow ....once again thanks for you time.
