### ISSUE TITLE
Remote-Debugging PODM application running in Linux

### ISSUE THREAD

**Issue by lalithabheemavarapu** [intel/intelRSD#107]
Hello,

Am working on Intel RSD PODM v2.3.2,my PODM application is running on Linux Ubuntu server on VMware virtual machine,and i have the PODM reference code in Intellij IDE in my windows environment.i want to debug the PODM application so i created a jar in Intellij and imported jar to Linux and started debugging. In Intellij under Run/debug configuration i added the linux server IP address and port & In my Linux am running following command to hit debug
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar SW.jar
![PODM-debug](https://user-images.githubusercontent.com/5384301/60645302-ed82b900-9e6a-11e9-84c5-f375bae13de3.PNG)
 when i execute the command it is asking for the --password-type,when i passed the database password still am getting exception.

![podm-debug-password](https://user-images.githubusercontent.com/5384301/60645478-55d19a80-9e6b-11e9-9946-f64575761bdf.PNG)

P.S. I have changed the /opt/pod-manager/wildfly/bin/standalone.conf by uncommenting the remote socket debugging & in standalone.sh -->  DEBUG_Mode= true
Can anyone please help me on this.

Thanks
Lalitha

**Comment by lalithabheemavarapu** [comment]
Can anyone knows any solution....

**Comment by ArturBaryla** [comment]
Hi lalithabheemavarapu,
You should create a war file, not a jar.
Try to execute in repository 
`./gradlew build`
In IntelliJ you can create remote run configuration to connect with wildfly, with example arguments for remote JVM:
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888`

**Comment by lalithabheemavarapu** [comment]
Hello ,
I created a war file and imported to Linux,and build the project  in Linux using ./gradlew build,
And added a remote run configuration under gradle project.whenever i click the debug button ,the debugger getting all the threads to get initiated and immediately the debugger is getting stopped.
![remore-run-gradle](https://user-images.githubusercontent.com/5384301/61027161-11547a80-a3e8-11e9-8d7e-f449d22a4082.PNG)
![debug-start](https://user-images.githubusercontent.com/5384301/61027169-14e80180-a3e8-11e9-9825-a8c26329fec0.PNG)
![debug-stopped](https://user-images.githubusercontent.com/5384301/61027178-17e2f200-a3e8-11e9-9e09-3d6b744f9208.PNG).

Can anyone help me on this....

**Comment by lalithabheemavarapu** [comment]
Hello ,
I created a war file and imported to Linux,and build the project  in Linux using ./gradlew build,
And added a remote run configuration under gradle project.whenever i click the debug button ,the debugger getting all the threads to get initiated and immediately the debugger is getting stopped.
![remore-run-gradle](https://user-images.githubusercontent.com/5384301/61027161-11547a80-a3e8-11e9-8d7e-f449d22a4082.PNG)
![debug-start](https://user-images.githubusercontent.com/5384301/61027169-14e80180-a3e8-11e9-9825-a8c26329fec0.PNG)
![debug-stopped](https://user-images.githubusercontent.com/5384301/61027178-17e2f200-a3e8-11e9-9e09-3d6b744f9208.PNG)

Can anyone help me on this....

**Comment by ArturBaryla** [comment]
Hello!
Please try to create "Run/Remote" configuration with that VM options:
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888`

In the screenshot you trying run Gradle configuration and set `address={portNumber}` not full address.

If your application is in different machine try to create SSH tunnel for example:
`ssh targetMachine@10.10.10.10 –L 8888:127.0.0.1:8787` 
Where targetMachine@10.10.10.10 is target user and address.
8888 is the local port where is IDE
8787 is debbuger port in the targetMachine (you can check that port in standalone.sh script)

**Comment by lalithabheemavarapu** [comment]
Thanks a alot @ArturBaryla ,i used "remote-debug" in gradle and now am able to debug PODM in my windows.
![Debug-PODM-work](https://user-images.githubusercontent.com/5384301/61199690-5e4e8e80-a711-11e9-9c1e-68ef7e4ecd5d.PNG)...
