### ISSUE TITLE
install PODM no error but not found OrientDB and WildFly

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#33]
Dear Intel
I download intel RSD Git last version 2.2 and compiled and deployed PODM,
following  332871-003 POD user guide, 
after install packages in guide  "3.3. Prerequisties" and "4. POD Manager Compilation",
and "5. Application server and Database Configuration" said that OrientDB and WildFly will be deployed after installed PODM .deb package,
could you help to support ? thank you
House

**Comment by zhlicen** [comment]
332871-003 is the guide for v1.2.
You should get the latest(v2.1) PODM guide [here]( https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/pod-manager-user-guide-v2-1.html), in which the orientdb is no longer needed

**Comment by tbykowsk** [comment]
Hi @housemic,

As @zhlicen has already mentioned, please use the latest available [PODM User Guide](https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/rack-scale-design-resources.html). The OrientDB database is no longer required, but PODM still runs within the Wildfly application server.
Does it answer your question?

**Comment by housemic** [comment]
Dear tbykowsk
the issue can be closed, thank you.
after deployed PODM, 
I checked service and log that PODM and wildfly was started
$ service --status-all
$ sudo service postgresql status
$ sudo service pod-manager status
$ tail /var/log/wildfly/console.log
$ tail /opt/pod-manager/wildfly/standalone/log/server.log
