### ISSUE TITLE
run cyMUX -f but have error message

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#35]
Dear Intel 
I prepare Ubuntu 14.04 LTS. and download Intel RSD Git last ver. 2.2.
I follow README file in the Git package \intelRSD-2.2\tools\CyMUX
to build the tool by make command ,
and Installing library on Ubuntu x86_64 target and binaries.

the README said "cyMUX should be run as a service during start up."
but I can see byMUX at service list and 
run 
/usr/bin/cyMUX -?
and 
/usr/bin/cyMUX -f
Error: CY7C65215: HW detection failed (or already bound by another process)

Please help to support the error message, thank you.
House

**Comment by tbykowsk** [comment]
Hi @housemic,

The cyMUX service in the Intel RSD reference hardware is used to i.a. detect blades on the drawer level. The service manages all asynchronous IPMB messages to and from [CY7C65215](http://www.cypress.com/documentation/datasheets/cy7c65215-usb-serial-dual-channel-uarti2cspi-bridge-capsense-and-bcd) device - which should be present in a system where the cyMUX is run.
You may find more about the cyMUX API in [this document](https://github.com/intel/intelRSD/blob/master/tools/CyMUX/cyMUX/cyMUX%20API.docx). You could also be interested in [the RSD Platform Hardware Guide](https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/platform-hardware-guide-v2-1.html).

**Comment by housemic** [comment]
Dear tbykowsk
1. Does cyMUX only support the hardware USB-Serial Bridge Controller CY7C65215 - Cypress Semiconductor ?
2. If I don't have the hardware CY7C65215, Can I startup cyMUX ?
thank you
House

**Comment by tbykowsk** [comment]
1.  CyMUX was only validated with CY7C65215, so it might not be fully compatible with other devices of this kind.
2. Unfortunately the required hardware must be present in order for cyMUX to work correctly.

**Comment by housemic** [comment]
Dear tbykowsk
the issue can be closed, thank you very much.
House
