### ISSUE TITLE
startup PSME compute simulator fail - error msg - RPC Error - METHOD_NOT_FOUND

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#36]
Dear Intel,
I startup PSME rest server success,
$ sudo ./psme-rest-server ../../application/config/psme-rest-server-configuration.json

but startup PSME compute simulator fail,  this is my steps,

1. Edit /home/user/IntelRSD/intelRSD-2-2/PSME/agent-simulator/compute/configuration.json
    "assetConfiguration" : {
        "input"  : "/home/user/IntelRSD/intelRSD-2-2/PSME/agent-simulator/compute/deep_discovery.xml",
        "schema" : "/home/user/IntelRSD/intelRSD-2-2/PSME/agent-simulator/compute/deep_discovery.xsd"
    },
    "service-uuid-file" : "/var/opt/psme/compute-service-uuid.json",

2. create directory in /var/opt/psme/
$ sudo mkdir /var/opt/psme

3. startup PSME compute simulator
$pwd
/home/user/IntelRSD/intelRSD-2-2/PSME/build/bin

$ sudo ./psme-compute-simulator ../../agent-simulator/compute/configuration.json

2018-01-10 13:46:11.637516758 - INFO  - compute-agent - MANUAL PSME BUILD; Built 13:42:27, 28-12-2017
2018-01-10 13:46:11.637569096 - DEBUG - configuration - Added file ../../agent-simulator/compute/configuration.json
2018-01-10 13:46:11.637629569 - WARN  - configuration - Cannot load default file
2018-01-10 13:46:11.637654782 - INFO  - configuration - Load file
2018-01-10 13:46:11.637715016 - INFO  - configuration - Loaded file ../../agent-simulator/compute/configuration.json
2018-01-10 13:46:11.637749701 - INFO  - configuration - Load internal defaults
2018-01-10 13:46:11.637850880 - INFO  - compute-agent - JSON Schema load!
2018-01-10 13:46:28.309609980 - ERROR - command-server - RPC Error : Exception -32601 - METHOD_NOT_FOUND: The method being requested is not available on this server: Unknown method: getTasksCollection
2018-01-10 13:46:28.309970204 - ERROR - command-server - RPC Error : Exception -32601 - METHOD_NOT_FOUND: The method being requested is not available on this server: Unknown method: getMetricDefinitionsCollection
2018-01-10 13:46:28.310301963 - ERROR - command-server - RPC Error : Exception -32601 - METHOD_NOT_FOUND: The method being requested is not available on this server: Unknown method: getMetrics

Please help to support, thank you.
House

**Comment by tbykowsk** [comment]
Hi @housemic,

The exception METHOD_NOT_FOUND appears when PSME Rest Server calls a method, which is not implemented an Agent. This error may be ignored if it does not affect any functionality which you require.

**Comment by housemic** [comment]
Dear tbykowsk,
so psme compute simulator has loaded deep_discovery.xml success,

and Can I see the hardware information in the PSME server ?

PSME REST server IP adderss is : 192.168.1.105
I use uBuntu 16.04 FoxPro to open the http server :
https://192.168.1.105:8443/redfish/v1 

it shows the Insecure connection :
Peer Certificate issuer is not recognized. 
HTTP Strict Transport Security: false 
HTTP Public Key Pinning: false
 
Certificate chain: 

-----BEGIN CERTIFICATE----- 
....
-----END CERTIFICATE----- 

after I import ca.crt, the error fixed,
but I still can not see anything in FoxPro
because it display nothing,
Could you help ? thank you

House

**Comment by tbykowsk** [comment]
Please refer to chapter _F.2_ in [the PSME User Guide](https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/psme-user-guide-v2-2.html).
What response do you receive if you change `"client-cert-required"` to `"false"` in the PSME Rest Server configuration file and restart the application?

I suggest to generate PSME Rest Server certificates using [psme-gen-serv-cert.sh](https://github.com/intel/intelRSD/blob/master/PSME/lui/OS/rootfs/usr/bin/psme-gen-serv-cert.sh) script:
`./psme-gen-serv-cert.sh --srv-cert=/etc/psme/certs/server.crt --srv-key=/etc/psme/certs/server.key`
The proposed default directory for certificates is `/etc/psme/certs`, but it can be modified in the configuration file.

**Comment by housemic** [comment]
Dear tbykowsk,
1. Can I see the hardware information in the PSME server ?

I have generated server.key and server.crt. and put them to PSME/build/certs/,
client-cert-required" to "false" nd restart,
I run PSME rest server success.

ubuntu 16.04 FoxPro open the PSME http server fail,
https://192.168.1.105:8443/redfish/v1
FoxPro display nothing

2. Does the hardware information only be displayed in POD Manager ?

House

**Comment by tbykowsk** [comment]
Ad 1. What do you receive when you connect on localhost via curl?
`curl -v -i -k https://localhost:8443/redfish/v1`

Does a http protocol work correctly?
`curl -v -i -k http://localhost:8888/redfish/v1`

Ad 2.  No, the PSME Rest Server is not limited to answer only to PODM.

**Comment by housemic** [comment]
Dear tbykowsk, 
after I started psme-rest-server and run curl command 
user@psme1:~$ curl -i -v -k https://localhost:8443/redflsh/v1
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: user-desktop (does not match 'localhost')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #1
* 	 subject: C=EX,O=Example Inc,CN=user-desktop
* 	 start date: Thu, 28 Dec 2017 08:17:40 GMT
* 	 expire date: Sat, 27 Jan 2018 08:17:40 GMT
* 	 issuer: C=EX,O=Example Inc,CN=user-desktop
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /redflsh/v1 HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 0
Content-Length: 0
< Date: Fri, 12 Jan 2018 07:14:28 GMT
Date: Fri, 12 Jan 2018 07:14:28 GMT

< 
* Connection #0 to host localhost left intact

Is it correct ? thanks
House

**Comment by tbykowsk** [comment]
Thanks @housemic,

Could you verify if your PSME Rest Server is using a configuration file where `connectors` are set this way?
```
        "connectors" : [
            {
                "use-ssl" : true,
                "certs-directory" : "/etc/psme/certs",
                "port": 8443,
                "thread-mode" : "select",
                "client-cert-required" : false
            },
            {
                "use-ssl" : false,
                "port": 8888,
                "redirect-port" : 8443,
                "thread-mode" : "select",
                "thread-pool-size" : 1
            }
        ]
```

You may also have a typo in your request - `redflsh` instead of `redfish`.
 Please check connection to 8888 port using the `http` protocol, not `https`.

**Comment by housemic** [comment]
Dear tbykowsk,

Configuration.json :

    "server": {
        "network-interface-name" : "enp0s20f0.4094",
        "connectors" : [
            {
                "use-ssl" : true,
                "certs-directory" : "/etc/psme/certs",
                "port": 8443,
                "thread-mode" : "select",
                "client-cert-required" : false
            },
            {
                "use-ssl" : false,
                "port": 8888,
                "redirect-port" : 8443,
                "thread-mode" : "select",
                "thread-pool-size" : 1
            }
        ]
    },


---------------------------------------------------------

curl -i -v -k https://localhost:8443/redflsh/v1



user@psme1:~$ curl -i -v -k https://localhost:8443/redflsh/v1
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: user-desktop (does not match 'localhost')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #1
* 	 subject: C=EX,O=Example Inc,CN=user-desktop
* 	 start date: Thu, 28 Dec 2017 08:17:40 GMT
* 	 expire date: Sat, 27 Jan 2018 08:17:40 GMT
* 	 issuer: C=EX,O=Example Inc,CN=user-desktop
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /redflsh/v1 HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 0
Content-Length: 0
< Date: Mon, 15 Jan 2018 09:08:56 GMT
Date: Mon, 15 Jan 2018 09:08:56 GMT

< 
* Connection #0 to host localhost left intact




------------------------------------------------

curl -i -v -k http://localhost:8888/redflsh/v1


user@psme1:~$ curl -i -v -k http://localhost:8888/redflsh/v1
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /redflsh/v1 HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 436
Content-Length: 436
< Content-Type: application/json
Content-Type: application/json
< Date: Mon, 15 Jan 2018 09:10:09 GMT
Date: Mon, 15 Jan 2018 09:10:09 GMT

< 
* Connection #0 to host localhost left intact
{"error":{"code":"Base.1.0.ResourceMissingAtURI","message":"The resource at the URI /redflsh/v1 was not found.","@Message.ExtendedInfo":[{"@odata.type":"#Message.v1_0_0.Message","MessageId":"Base.1.0.ResourceMissingAtURI","Message":"Invalid endpoint in /redfish/v1 namespace.","RelatedProperties":[],"MessageArgs":[],"Resolution":"Place a valid resource at the URI or correct the URI and resubmit the request.","Severity":"Critical"}]}}user@psme1:~$ 



---------------------------------------------------------

I started psme-rest-server and psme-compute-simulator
check connection to 8888 port using the http in FireFox Web Browser

http://localhost:8888/redflsh/v1

but only have error message
The resource at the URI /redflsh/v1 was not found


![screenshot from 2018-01-15 17-20-43](https://user-images.githubusercontent.com/35086928/34971020-f8318f50-fab2-11e7-9919-c464e7d5e9a3.png)

**Comment by tbykowsk** [comment]
You still have an error in your URLs - it should be `/redfish/v1`, not `/redflsh/v1`.
Also double check that you are passing as a parameter the path to the modified configuration file (when you are starting the PSME Rest Server).

**Comment by housemic** [comment]
Dear tbykowsk,

curl -i -v -k http://localhost:8888/redfish/v1


user@psme1:~$ curl -i -v -k http://localhost:8888/redfish/v1
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /redfish/v1 HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Connection: Keep-Alive
Connection: Keep-Alive
< Content-Length: 973
Content-Length: 973
< Content-Type: application/json
Content-Type: application/json
< Date: Wed, 17 Jan 2018 06:39:35 GMT
Date: Wed, 17 Jan 2018 06:39:35 GMT

< 
* Connection #0 to host localhost left intact
{"@odata.context":"/redfish/v1/$metadata#ServiceRoot.ServiceRoot","@odata.id":"/redfish/v1","@odata.type":"#ServiceRoot.v1_1_1.ServiceRoot","Id":"RootService","Name":"PSME Service Root","Description":"Service Root description","RedfishVersion":"1.1.0","UUID":"80330acc-f9d3-11e7-aef4-27af4715432f","EventService":{"@odata.id":"/redfish/v1/EventService"},"UpdateService":{"@odata.id":"/redfish/v1/UpdateService"},"Tasks":{"@odata.id":"/redfish/v1/TaskService"},"Registries":{"@odata.id":"/redfish/v1/Registries"},"Chassis":{"@odata.id":"/redfish/v1/Chassis"},"Systems":{"@odata.id":"/redfish/v1/Systems"},"Managers":{"@odata.id":"/redfish/v1/Managers"},"Fabrics":{"@odata.id":"/redfish/v1/Fabrics"},"TelemetryService":{"@odata.id":"/redfish/v1/TelemetryService"},"Oem":{"Intel_RackScale":{"@odata.type":"#Intel.Oem.ServiceRoot","ApiVersion":"2.2.0","Services":{"@odata.id":"/redfish/v1/Services"},"EthernetSwitches":{"@odata.id":"/redfish/v1/EthernetSwitches"}}},"Links":{}}user@psme1:~$ 

-------------------------------------------------------

use uBuntu 16.04 Fox Pro browser to see :

http://localhost:8888/redfish/v1

![screenshot from 2018-01-17 14-41-28](https://user-images.githubusercontent.com/35086928/35041645-6b471ae2-fbc0-11e7-8a68-ffbc994aec99.png)

**Comment by tbykowsk** [comment]
The output is okay. You should receive the same response via the https protocol if your configuration is correct.

**Comment by housemic** [comment]
Dear tbykowsk,
the issue can be closed, thank you
House
