### ISSUE TITLE
Question for display hardware information when run PSME REST server and compute simulator

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#39]
Dear Intel
when I run PSME REST server and PSME compute simulator, but don't run PODM,
PSME compute simulator loaded deep_discovery.xml that have pseudo hardware (HW) information,
Could I display the hardware information in PSME server ? thanks you.

1. PSME REST Server running 
![screenshot from 2018-01-10 13-36-28](https://user-images.githubusercontent.com/35086928/35131664-6d472d62-fd02-11e7-95cf-dcb30a3c004a.png)

![screenshot from 2018-01-10 13-37-18](https://user-images.githubusercontent.com/35086928/35131668-726f4478-fd02-11e7-9440-d7245bdce82a.png)

2. PSME compute simulator running
![screenshot from 2018-01-10 13-47-20](https://user-images.githubusercontent.com/35086928/35131705-a70e6c18-fd02-11e7-9d59-4994b58573f4.png)

![screenshot from 2018-01-10 13-47-40](https://user-images.githubusercontent.com/35086928/35131717-b2646464-fd02-11e7-9fef-820026f47321.png)

3. in PSME REST server
use uBuntu 16.04 FireFox browser , but not found hardware information from PSME compute simulator :

http://localhost:8888/redfish/v1

![screenshot from 2018-01-17 14-41-28](https://user-images.githubusercontent.com/35086928/35131780-1d33732a-fd03-11e7-82c6-486c83b2cc64.png)

**Comment by tbykowsk** [comment]
Hi @housemic,

You should be able to display information about compute modules at:
`https://IP:8443/redfish/v1/Systems/`

Also make sure that PSME Compute Simulator is the only agent connected to a given instance of PSME Rest Server.

**Comment by housemic** [comment]
Dear tbykowsk,
I run only one PSME REST Server and only one PSME compute simulator.
use FireFox Web browser to  https://192.168.1.105:8443/redfish/v1 
and  https://192.168.1.105:8443/redfish/v1/Systems   but display  nothing 
192.168.1.105 is PSME1 IP

**Comment by tbykowsk** [comment]
It looks like this issue is also related to #36, you should be able to see at least an empty list of Systems even if no PSME Agent is connected.

**Comment by housemic** [comment]
Dear tbykowsk,
so if PSME REST server is running,
but PSME agent is not running,
and PSME compute simulator is running,

in PSME REST server web server -  https://192.168.1.105:8443/redfish/v1  ,
Can't  I  see the hardware information in deep_discovery.xml loaded by PSME compute simulator ?

House

**Comment by tbykowsk** [comment]
Empty asset lists are shown in REST API if only PSME REST Server is running.
You need to start PSME Compute Simulator (or PSME Compute Agent if you have supported hardware) in order to see any Systems present.
