### ISSUE TITLE
PSME Server web server - Systems page has authorization error

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#40]
Dear Intel,

when I go to PSME Server web server, can see the information in the following picture ,
![screenshot from 2018-01-19 17-36-27](https://user-images.githubusercontent.com/35086928/35145376-8e90a472-fd42-11e7-9e01-d953f63c8e9a.png)

but when go to Systems page, get error message : "While accessing the resource at /redfish/v1/Systems, the service received an authorization error."
resolution : Ensure that the appropriate access is provided for the service in order for it to access the URI.
![screenshot from 2018-01-19 17-36-35](https://user-images.githubusercontent.com/35086928/35145439-c0cd3c52-fd42-11e7-9303-a7b982b29f9f.png)

Could you help ? thank you
House

**Comment by tbykowsk** [comment]
Hi @housemic,

In order to access protected resources use the `https` protocol:

`https://IP:8443/redfish/v1/Systems/`

**Comment by housemic** [comment]
How to solve the problem ?
Do I generate PKCS #12 key based on root key ?
and import the key into FireFox Web browser ?
thank you
House

**Comment by tbykowsk** [comment]
If your PSME Rest Server configuration has `"client-cert-required" : false` set, then the key does not need to be imported. You should receive a response via `https` like in issue #36.
Please verify whether your configuration contains a valid JSON and that the correct config file is applied when you start the PSME Rest Server.

**Comment by housemic** [comment]
Dear

I checked Configuration.json is "client-cert-required" : false


PSME REST server startup command is :

cd /home/user/IntelRSD/intelRSD-2-2/PSME/build/bin

sudo ./psme-rest-server ../../application/config/psme-rest-server-configuration.json


------------------------------------------------------
pwd
/home/user/IntelRSD/intelRSD-2-2/PSME/application/config/

psme-rest-server-configuration.json :

{
    "server": {
        "url": "http://localhost:8888",
        "network-interface-name" : "enp0s20f0.4094"
    },
    "registration": {
        "port": 8383,
        "minDelay": 3
    },
    "commands": {
        "generic": "Registration"
    },
    "eventing" : {
        "enabled" : false,
        "address": "localhost",
        "port" : 5567,
        "poll-interval-sec" : 20
    },
    "rest-server" : {
        "storage-service-mode" : false
    },
    "service-uuid-file" : "/etc/psme/service_uuid.json",
    "subscription-config-file" : "/tmp/subscriptions",
    "rmm-present" : false,
    "logger" : {
        "app" : {
            "level" : "INFO",
            "timeformat" : "DATE_NS",
            "color" : true,
            "output" : true,
            "tagging" : true,
            "moredebug" : false,
            "streams" : [
                 {
                    "type" : "STDOUT"
                 }
            ]
        }
    }
}



------------------------------------------------------
pwd
/home/user/IntelRSD/intelRSD-2-2/PSME/application/


configuration.json :


{
    "server": {
        "network-interface-name" : "enp0s20f0.4094",
        "connectors" : [
            {
                "use-ssl" : true,
                "certs-directory" : "/etc/psme/certs",
                "port": 8443,
                "thread-mode" : "select",
                "client-cert-required" : false
            },
            {
                "use-ssl" : false,
                "port": 8888,
                "redirect-port" : 8443,
                "thread-mode" : "select",
                "thread-pool-size" : 1
            }
        ]
    },
    "event-service" : {
        "delivery-retry-attempts" : 3,
        "delivery-retry-interval-seconds" : 60
    },
    "ssdp-service" : {
        "enabled" : true,
        "announce-interval-seconds" : 0,
        "ttl" : 2
    },
    "rmm-present" : false,
    "registration": {
        "port": 8383,
        "minDelay": 3
    },
    "commands": {
        "generic": "Registration"
    },
    "eventing" : {
        "address": "localhost",
        "port" : 5567,
        "poll-interval-sec" : 20
    },
    "rest" : {
        "service-root-name" : "PSME Service Root"
    },
    "database": {
        "location": "/var/opt/psme",
        "retention-interval-sec": 600,
        "retention-outdated-sec": 2419200
    },
    "service-uuid-file" : "/var/opt/psme/rest-server-service-uuid.json",
    "subscription-config-file" : "/var/opt/psme/subscriptions",
    "logger" : {
        "app" : {
            "level" : "INFO",
            "timeformat" : "DATE_NS",
            "color" : true,
            "output" : true,
            "tagging" : true,
            "moredebug" : false,
            "streams" : [
                 {
                    "type" : "STDOUT"
                 }
            ]
        }
    }
}


------------------------------------------------------

when I use FireFox to open the web 

https://192.168.1.105:8443/redfish/v1

display nohing

![screenshot from 2018-01-22 20-52-43](https://user-images.githubusercontent.com/35086928/35223443-5b32b152-ffbc-11e7-9334-e3a9b23e1f13.png)

but found security message 

![screenshot from 2018-01-22 20-52-55](https://user-images.githubusercontent.com/35086928/35223467-6bf7842c-ffbc-11e7-9a0b-d428a3e03e09.png)

Does PSME server need certificate  ?
thanks
House

**Comment by tbykowsk** [comment]
Only the configuration file which is provided as a parameter is applied.

You start PSME Rest Server with a configuration that has no `"client-cert-required" : false` set:
> sudo ./psme-rest-server ../../application/config/psme-rest-server-configuration.json

Run the application with the configuration file where this flag is present:
`sudo ./psme-rest-server ../../application/configuration.json `

**Comment by housemic** [comment]
Dear tbykowsk
I use the command and PSME web server is ok
sudo ./psme-rest-server ../../application/configuration.json

the issue can be closed, thank you very much.
House

the attachment is PSME compute simulator's assets, display HW info success -

![screenshot from 2018-01-23 16-25-40](https://user-images.githubusercontent.com/35086928/35269817-172e9bae-0068-11e8-8ced-6ee79c5105fb.png)
