### ISSUE TITLE
Don't find ca.pfx in PODM server when creating client certificate

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#42]
Dear intel

I follow PODM user guide 2.2 :

4.3.1 Creating client certificate
Example 2 : Create client certificate and sign it with existing CA certificate.

   cd /var/lib/pod-manager

   sudo pod-manager-certificate-creation.sh --ca-certificate /path/to/ca/file/ca.pfx --client-certificate "C=PL,ST=State,L=locality,O=organization,CN=fqdn_or_ip"

but I don't find ca.pfx in PODM server,
Could you help ?
thank you
House

**Comment by tbykowsk** [comment]
Hi @housemic,

You are looking at Example 2, which requires an existing CA certificate.
If you do not have one, then run the command from Example 1.

You do not need to use Example 2, if you have already used Example 1.

**Comment by housemic** [comment]
Dear tbykowsk,
the issue can be closed, thank you.
House
