### ISSUE TITLE
Qestions for additional PODM compute assets after modify event.json and install nodejs Simulaors

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#43]
Dear intel,
I have questions that
after modify event.json and install nodejs Simulaors and run PSME Mock ,
there are additional PODM compute assets (8 hosts) -
   10-s-1, 3-s-1, 8-s-1, ..... , 6-s-1.

Do they come from nodejs Simulaors ?
How to check ? thank you
House

---------------------------------------------

cat /etc/pod-manager/events.json
{
  "Northbound": {
    "DeliveryRetryAttempts": 2,
    "DeliveryRetryIntervalSeconds": 1
  },
  "Southbound": {
    "EventSubscriptionIntervalSeconds": 90,
    "BufferedEventProcessing" : {
      "ProcessingWindowSizeInSeconds": 5
    },
    "ServicesConfiguration": [
      {
        "ServiceType": "psme",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "rss",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "rmm",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "inband",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      }
    ]
  }
}

-----------------------------------------------
run PSME Mock 

![screenshot from 2018-01-24 19-34-53](https://user-images.githubusercontent.com/35086928/35389887-56300b3c-0214-11e8-9d97-a2e69f67d204.png)

------------------------------------------------
PSME Mock -

http://127.0.0.1:9443/redfish/v1

http://127.0.0.1:9443/redfish/v1/Systems

http://127.0.0.1:9443/redfish/v1/Systems/1

can see detail hardware information from PSME Mock :
![screenshot from 2018-01-24 17-52-30](https://user-images.githubusercontent.com/35086928/35390206-89c91690-0215-11e8-9344-31799d3ec3f0.png)

![screenshot from 2018-01-24 17-53-01](https://user-images.githubusercontent.com/35086928/35390222-940fc5ea-0215-11e8-8013-9a47577ee097.png)

------------------------------------------------

in PODM Server Web ,
https://localhost:8443/redfish/v1/Systems
can found compute assets (8 hosts) -
![screenshot from 2018-01-24 21-24-45](https://user-images.githubusercontent.com/35086928/35389923-81899140-0214-11e8-9110-c4e70b462a13.png)

![screenshot from 2018-01-24 17-57-48](https://user-images.githubusercontent.com/35086928/35390079-27257ce0-0215-11e8-86f5-a246bfe32a9c.png)

**Comment by tbykowsk** [comment]
Hi @housemic,

You may run `psme_mock.js` with [custom options](https://github.com/intel/intelRSD/blob/master/Simulators/simulators/mock_entry_points/psme_mock.js) to modify the number of assets.
If you have changed network interfaces to `localhost` in PODM configuration, then all visible Systems come from nodejs Simulators.

**Comment by housemic** [comment]
Dear tbykowsk,
I checked the additional PODM compute assets (8 hosts) -
10-s-1, 3-s-1, 8-s-1, ..... , 6-s-1.
comes from PSME Mock,

Why PSME Mock has only one PSME host,
but PODM display 8 hosts ?

I think that when PSME Mock run, it assign a new UUID,
and PODM register the UUID as a new host,
so after I run PSME Mock 8 times,
PODM register 8 PSME Mock data and add 8 hosts,
Does it right ? thank you
House

**Comment by tbykowsk** [comment]
Hi @housemic,

If all systems in PODM have the same properties as in `deep_discovery.xml` file, then they are coming from a PSME Compute Agent Simulator. Each run of the agent may generate a new UUID, which is visible in PODM as a separate system.

**Comment by housemic** [comment]
Dear tbykowsk,
the issue can be closed, thank you.
House
