### ISSUE TITLE
DiscoveryCancelable flag in discovery.json

### ISSUE THREAD

**Issue by rwleea** [intel/intelRSD#46]
Dear Intel,

I have a question about discovery config, I check for pod-manager source code,
I guess DiscoveryCancelable in discovery.json is used for cancel discovery job(polling external service job),

But I don't know why I need this flag, I didn't find any document interpret about this configuration.
could you please give me some hint about the usage of this configuration? #

**Comment by tbykowsk** [comment]
Hi @rwleea,

Discovery job is run by PODM at regular time intervals, which can be configured in `discovery.json` file (by default it is 10 minutes):

```
{
  "MaxComputerSystemsCountPerDrawerBeingDeepDiscovered": 1,
  "DeepDiscoveryEnabled": false,
  "DiscoveryIntervalSeconds": 600,
  "DiscoveryCancelable": false
}
```


During this action a full scan of services (e.g. PSME) is performed, duration time depends on a service type/size/implementation/etc.
All read-write operations within a single service are executed sequentially. Therefore, while a discovery job is in progress, then all incoming POST/PATCH/DELETE requests will wait for the job to finish.
Usually, waiting of the requests is unnoticeable, but it may happen that some services require a relatively longer time for discovery job to complete – in this case `DiscoveryCancelable` flag comes into play.
When the flag is enabled, then the discovery job in progress will be cancelled, if a POST/PATCH/DELETE request is received. The request will be executed without a delay.

**Comment by rwleea** [comment]
Hi @tbykowsk,

Thanks for your interpretation, I got it.
