### ISSUE TITLE
Safe-string-0.0.1 library compilation error

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#47]
Dear intel ,

I install PSME make all j8 has error on ubuntu 16.04 but pass on Fedora 23

the following is my steps, please support, thank you -
--------------------------------------------------------

ubuntu 16.04
select [About the Computer] -> [Install Update]
after download and installed completed, reboot.

sudo apt-get install cmake clang gcc-5 g++-5 libgcrypt20-dev libncurses5-dev \
libnl-3-dev libudev-dev libglibmm-2.4-dev libglib3.0-cil-dev libxml++2.6-dev \
libgnutls-dev libnl-route-3-dev flex bison valgrind doxygen cmake cpp ccache \
build-essential linux-libc-dev libmpc-dev libstdc++6 libcurl4-openssl-dev \
libmicrohttpd-dev lcov libxml++2.6-dev libnl-3-dev libnl-route-3-200 libudev-dev \
libgcrypt20-dev libgnutls-dev libpopt-dev libusb-dev patch \
libdevmapper-dev liblvm2-dev unzip libnl-genl-3-dev libblkid-dev debsigs \
debsig-verify gnupg libusb-1.0-0-dev

cd /home/user/intelRSD/intelRSD-2-2/PSME/third_party

./download.sh

user@psme4:~/intelRSD/intelRSD-2-2/PSME/third_party$ ls -al
total 21380
drwxrwxr-x  2 user user    4096  鈭?  3 03:44 .
drwxrwxr-x 12 user user    4096  鈭?  3 03:53 ..
-rw-rw-r--  1 user user 3498551  ?? 19  2017 curl-7.54.0.tar.gz
-rwxr-xr-x  1 user user     958 ?? 22 16:23 download.sh
-rw-rw-r--  1 user user  192341  鈭?  3 03:44 EosSdk-stubs-1.13.0.tar.gz
-rw-rw-r--  1 user user 2897695  銝  18  2017 gcrypt-1.7.6.tar.bz2
-rw-rw-r--  1 user user  371264  鈭?  3 03:44 gmock-1.7.0.zip
-rw-rw-r--  1 user user 1671264  鈭?  6  2012 gmp-5.0.5.tar.xz
-rw-rw-r--  1 user user 7166932  鈭? 12  2017 gnutls-3.5.9.tar.xz
-rw-rw-r--  1 user user  813060  鈭? 28  2017 gpg-error-1.27.tar.bz2
-rw-rw-r--  1 user user  633003  鈭?  3 03:44 gtest-1.7.0.zip
-rw-rw-r--  1 user user  772570  鈭?  6  2016 ipmitool-1.8.17.tar.bz2
-rw-rw-r--  1 user user 1309560  鈭?  3  2017 libmicrohttpd-0.9.54.tar.gz
-rw-rw-r--  1 user user 1887927  ??  1  2016 nettle-3.3.tar.gz
-rw-rw-r--  1 user user     291 ?? 22 16:23 README.md
-rw-rw-r--  1 user user  244202  鈭?  3 03:44 safestring-0.0.1.zip
-rw-rw-r--  1 user user  397048  銝?  5  2008 uuid-1.6.2.tar.gz

-------------------------------------------------------

Building release version:

cd /home/user/intelRSD/intelRSD-2-2/PSME

mkdir build

cd /home/user/intelRSD/intelRSD-2-2/PSME/build

sudo cmake ..

-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/intelRSD/intelRSD-2-2/PSME/build

-------------------------------------------------------

sudo make all -j8

 sudo make all -j8
Scanning dependencies of target ipmi-base
Scanning dependencies of target base64
Scanning dependencies of target generic_mdr
Scanning dependencies of target logger
Scanning dependencies of target sysfsref
Scanning dependencies of target md5
Scanning dependencies of target uuid
Scanning dependencies of target database
[  0%] Building CXX object common/mdr/CMakeFiles/generic_mdr.dir/src/printers.cpp.o
[  1%] Building CXX object common/base64/CMakeFiles/base64.dir/src/base64.cpp.o
[  1%] Building CXX object common/sysfs/CMakeFiles/sysfsref.dir/src/path.cpp.o
[  1%] Building C object common/md5/CMakeFiles/md5.dir/src/md5.c.o
[  1%] Building CXX object common/database/CMakeFiles/database.dir/src/database.cpp.o
[  1%] Building CXX object common/uuid/CMakeFiles/uuid.dir/uuid-1.6.2/uuid++.cc.o
[  1%] Building C object common/logger/CMakeFiles/logger.dir/src/logger.c.o
[  1%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/connection_data.cpp.o
[  1%] Linking C static library ../../lib/libmd5.a
[  1%] Building CXX object common/logger/CMakeFiles/logger.dir/src/logger.cpp.o
[  1%] Building C object common/uuid/CMakeFiles/uuid.dir/uuid-1.6.2/uuid.c.o
[  1%] Built target md5
[  2%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/bridge_info.cpp.o
In file included from /home/user/intelRSD/intelRSD-2-2/PSME/build/include/safe-string/safe_lib.h:59:0,
                 from /home/user/intelRSD/intelRSD-2-2/PSME/build/include/safe-string/safe_mem_lib.h:36,
                 from /home/user/intelRSD/intelRSD-2-2/PSME/common/uuid/uuid-1.6.2/uuid.c:54:
/home/user/intelRSD/intelRSD-2-2/PSME/build/include/safe-string/safe_str_lib.h:268:8: error: unknown type name ?char_t?? extern wchar_t *
        ^
compilation terminated due to -Wfatal-errors.
common/uuid/CMakeFiles/uuid.dir/build.make:86: recipe for target 'common/uuid/CMakeFiles/uuid.dir/uuid-1.6.2/uuid.c.o' failed
make[2]: *** [common/uuid/CMakeFiles/uuid.dir/uuid-1.6.2/uuid.c.o] Error 1
CMakeFiles/Makefile2:600: recipe for target 'common/uuid/CMakeFiles/uuid.dir/all' failed
make[1]: *** [common/uuid/CMakeFiles/uuid.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/management_controller.cpp.o
[  2%] Building CXX object common/mdr/CMakeFiles/generic_mdr.dir/src/generic_entry_point.cpp.o
[  2%] Linking CXX static library ../../lib/libbase64.a
[  2%] Built target base64
[  2%] Building CXX object common/logger/CMakeFiles/logger.dir/src/logger_options.cpp.o
[  2%] Building CXX object common/database/CMakeFiles/database.dir/src/file_database.cpp.o
[  2%] Building CXX object common/database/CMakeFiles/database.dir/src/persistent_attributes.cpp.o
[  2%] Building CXX object common/logger/CMakeFiles/logger.dir/src/logger_factory.cpp.o
[  2%] Linking CXX static library ../../lib/libgeneric_mdr.a
[  2%] Built target generic_mdr
[  3%] Building CXX object common/sysfs/CMakeFiles/sysfsref.dir/src/sysfs_interface.cpp.o
[  3%] Building CXX object common/sysfs/CMakeFiles/sysfsref.dir/src/abstract_sysfs_interface.cpp.o
[  3%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/ipmi_controller.cpp.o
[  3%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_alloc.c.o
[  3%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_buffer.c.o
[  3%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/ipmi_interface.cpp.o
[  3%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_color.c.o
[  3%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/ipmi_interface_factory.cpp.o
[  3%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/message.cpp.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_level.c.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/request.cpp.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/response.cpp.o
[  4%] Linking CXX static library ../../lib/libsysfsref.a
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_list.c.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_stream.c.o
[  4%] Built target sysfsref
[  4%] Building CXX object common/logger/CMakeFiles/logger.dir/src/logger_stream.cpp.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/response_error.cpp.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/sel_record.cpp.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/logger_time.c.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/stream/logger_stream_config.c.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/stream/logger_stream_file.c.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/stream/logger_stream_socket.c.o
[  4%] Building C object common/logger/CMakeFiles/logger.dir/src/stream/logger_stream_standard.c.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/sel.cpp.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/utils/byte_buffer.cpp.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/telemetry/telemetry_hub.cpp.o
[  4%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/utils/sdv/mdr_region_accessor.cpp.o
[  4%] Linking CXX static library ../../lib/liblogger.a
[  4%] Built target logger
[  5%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/utils/sdv/purley_mdr_region_accesor.cpp.o
[  5%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/utils/sdv/grantley_mdr_region_accessor.cpp.o
[  5%] Building CXX object common/ipmi/src/CMakeFiles/ipmi-base.dir/utils/sdv/linear_to_double.cpp.o
[  5%] Linking CXX static library ../../lib/libdatabase.a
[  5%] Built target database
[  5%] Built target ipmi-base
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
user@psme4:~/intelRSD/intelRSD-2-2/PSME/build$ 

-------------------------------------------------------

**Comment by tbykowsk** [comment]
Hi @housemic,

It seems that recently the source code of "_safe-string-0.0.1.zip_" have been changed, but its version number remained the same. It is an external dependency for our project, but we will attempt to resolve this problem.

In the meantime, please place the attached older version of [safestring-0.0.1.zip](https://github.com/intel/intelRSD/files/1694385/safestring-0.0.1.zip) in your `third_party` directory and run building again.

**Comment by housemic** [comment]
Dear tbykowsk,
the issue can be closed, thank you.

make all -j8 pass after use old version of  safestring-0.0.1.zip,
House

**Comment by tbykowsk** [comment]
Thank you for your feedback @housemic,

I will leave this issue open until a permament solution is applied.

**Comment by RobertCMa** [comment]
Conclude the issue as 2.3 reference code, including the solution, is published.
