### ISSUE TITLE
Question for PODM web service refresh time to change compute assets status

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#49]
Dear intel -
the question is related to -
run PSME server and compute simulator and PODM but not found compute assets #38

in PODM -  https://localhost:8443/redfish/v1/Systems/1-s-10
I can see the web page - Status - State  is enabled,
and if I shutdown PSME Server and PSME compute simulator, 
and wait about 5 ~ 10 minutes, the web page - Status - State  is changed to Absent,

my question is - 
1. What is the setting (configuration file) about the PODM web service refresh time  ?

2. Can I change the setting ? 
thank you
House

**Comment by tbykowsk** [comment]
Hi @housemic,

Discovery job is run by PODM at regular time intervals, which can be changed in `/etc/pod-manager/discovery.json` configuration file:
`"DiscoveryIntervalSeconds": 600`

PSME Compute Agent (not PSME Compute Simulator Agent) immediately sends an event to PODM when a system is removed, so there is no delay in the status change.

**Comment by housemic** [comment]
Dear tbykowsk,
The issue can be closed, thank you.
in /etc/pod-manager/discovery.json configuration file:
"DiscoveryIntervalSeconds": 600
Change to
"DiscoveryIntervalSeconds": 120

Web service display fresh time is also changed by the setting.

House
