### ISSUE TITLE
Question - PSME compute agent - How to send IPMI OEM command to BMC

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#52]
Dear intel -
the question is related to Questions how PSME compute agent send IPMI commands to BMC AST2400 2500 and remove CY7C65215   #48,
Currently I can modify code of PSME compute agent to send Standard IPMI command (ex - Get Device ID) to BMC,

but If I want to add IPMI OEM command, need to add new Net function ID, new command ID,
Could you have suggestions ? thank you.
House

**Comment by tbykowsk** [comment]
Hi @housemic,

I would suggest you to add a new IPMI command based on existing ones. You can find their headers in [this catalogue](https://github.com/intel/intelRSD/tree/master/PSME/common/ipmi/include/ipmi/command) and implementations [there](https://github.com/intel/intelRSD/tree/master/PSME/common/ipmi/src/command). The IPMI commands inherit from common [request](https://github.com/intel/intelRSD/blob/master/PSME/common/ipmi/include/ipmi/request.hpp) and [response](https://github.com/intel/intelRSD/blob/master/PSME/common/ipmi/include/ipmi/request.hpp) structures, which source code along with comments should be quite self-explanatory.

**Comment by RobertCMa** [comment]
Hi @housemic ,

Will need to conclude the issue. It will move to close if staying inactivity in the following days. Feel free to open a new one if needed.

**Comment by housemic** [comment]
Dear RobertCMa,
the issue can be closed, thank you.
House
