### ISSUE TITLE
Question - PSME compute agent - Can it find MUX or BMC devices without IP address settings

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#53]
Dear intel -
the question is related to Questions how PSME compute agent send IPMI commands to BMC AST2400 2500 and remove CY7C65215 #48,
Currently I can modify code of PSME compute agent to send Standard IPMI command (ex - Get Device ID) to BMC,

PSME compute agent start command is - 
./psme-compute ../../agent/compute/configuration.json

BMC IP address is 192.168.1.106, so add IP address in configuration.json 
"managers": [
        {
            "slot" : 1,
            "switchPortIdentifier" : "sw0p37",
            "ipv4": "192.168.1.106",
            "username": “xxx",
            "password": “xxx",
            "port": 623,
            "serialConsoleEnabled": true
        }

Please help the questions, thank you -

Question 1 - in intel RSD 2.2, if do not setup BMC IP address in configuration.json, Can PSME compute agent find the BMC ? 

Question 2 - related to Question 1, Does PSME compute agent find the BMC devices by SSDP (Simple Service Discovery Protocol) ?

Question 3 - related to Question 1, Can we modify code to implement Question 1's request ? 

thank you. 
House

**Comment by tbykowsk** [comment]
Hi @housemic,

Ad 1. No, a BMC IP address along with a username and a password must be configured manually.

Ad 2. No, SSDP is used by PODM to detect PSME services, not to discover BMCs.

Ad 3. Feel free to modify the source code to suit your needs, but how you do it is up to you. We are currently not planning such a change.

**Comment by housemic** [comment]
Dear tbykowsk,
the issue can be closed, thank you.
House
