### ISSUE TITLE
Question - Can PSME compute agent auto find new BMC

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#54]
Dear intel ,
the question is related to #53,
Question - PSME compute agent - Can it find MUX or BMC devices without IP address settings,

if new computer server with BMC was added into network,
Can PSME compute agent auto find the new BMC ? 
thank you
currently I need to add slot information into configuration.json.
House

**Comment by tbykowsk** [comment]
Hi @housemic,

No, PSME Compute Agent requires that MUX/BMC addresses with which communication should be established are in a configuration file.

**Comment by housemic** [comment]
Dear tbykowsk,
the question can be closed, thank you.
House
