### ISSUE TITLE
Question - PODM wildfly fail - 404-Not Found - after run PSME Mock and can not recovery

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#57]
Dear intel,
the question is related to #38 -
run PSME server and compute simulator and PODM but not found compute assets 

I found that
I installed PODM and its wildfly work normally,
go to https://localhost:8443/redfish/v1 , I can see odata.

but when I run PSME Mock (nodejs Simulator) in the same computer with PODM,
go to https://localhost:8443/redfish/v1 ,but I got error message - 404-Not Found,

I must modify  /etc/pod-manager/events.json
to change the settings from - "NetworkInterfaceName": "eth0.4094",
to - "NetworkInterfaceName": "lo",

then go to https://localhost:8443/redfish/v1 , I can see odata.

Question 1 - Is it an issue ? thank you.

Question 2 - How to recovery PODM ?
                     if I recovery  /etc/pod-manager/events.json  and wildfly will fail.

thank you
House

**Comment by RobertCMa** [comment]
Hi @housemic,

For Q1, the rack and the network setup may vary among different user configuration. As mentioned in #38, modifying the "NetworkInterfaceName" is to specify the communication path. This option is reserved for the flexible adjustment.

For Q2, can elaborate more about the "recovery PODM"?  Will it work to restart the PODM service of "sudo service pod-manager restart" ?

**Comment by housemic** [comment]
Dear RobertCMa ,
for Question 2 - 
before I run PSME Mock, PODM wildfly is OK,
go to https://localhost:8443/redfish/v1 , I can see odata.

but after I run PSME Mock, 
go to https://localhost:8443/redfish/v1 ,but I got error message - 404-Not Found,
the PODM seems to be modified something.

House

**Comment by housemic** [comment]
Dear RobertCMa ,
1. if I do not modify /etc/pod-manager/events.json
   to change the settings from - "NetworkInterfaceName": "eth0.4094",
                                         to - "NetworkInterfaceName": "lo",
   it does not work to restart the PODM service - "sudo service pod-manager restart" .

2. the following is my steps -
after run PSME Mock -
![screenshot from 2018-03-21 12-00-42](https://user-images.githubusercontent.com/35086928/37708903-5ac9af04-2d43-11e8-91bb-994b14cd1403.png)

---------------------------------------------------------------

cat /etc/pod-manager/events.json


{
  "Northbound": {
    "DeliveryRetryAttempts": 2,
    "DeliveryRetryIntervalSeconds": 1
  },
  "Southbound": {
    "EventSubscriptionIntervalSeconds": 90,
    "BufferedEventProcessing" : {
      "ProcessingWindowSizeInSeconds": 5
    },
    "ServicesConfiguration": [
      {
        "ServiceType": "psme",
        "NetworkInterfaceName": "eth0.4094",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "rss",
        "NetworkInterfaceName": "eth0.4093",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "rmm",
        "NetworkInterfaceName": "eth0.4094",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "inband",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      }
    ]
  }
}

---------------------------------------------------------------

https://localhost:8443/redfish/v1

404-Not Found

https://localhost:8443/redfish/v1/Systems

404-Not Found

![Uploading Screenshot from 2018-03-21  16-26-07.png…]()

![screenshot from 2018-03-21 15-38-50](https://user-images.githubusercontent.com/35086928/37708817-028cd5a0-2d43-11e8-9aa2-0f37f71f28dc.png)

---------------------------------------------------------------

sudo gedit  /etc/pod-manager/events.json



{
  "Northbound": {
    "DeliveryRetryAttempts": 2,
    "DeliveryRetryIntervalSeconds": 1
  },
  "Southbound": {
    "EventSubscriptionIntervalSeconds": 90,
    "BufferedEventProcessing" : {
      "ProcessingWindowSizeInSeconds": 5
    },
    "ServicesConfiguration": [
      {
        "ServiceType": "psme",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "rss",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "rmm",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      },
      {
        "ServiceType": "inband",
        "NetworkInterfaceName": "lo",
        "PodManagerIpAddress": null
      }
    ]
  }
}


---------------------------------------------------------------

sudo service pod-manager restart


sudo service pod-manager status


---------------------------------------------------------------
https://localhost:8443/redfish/v1

ok, wildfly work normally.

https://localhost:8443/redfish/v1/Systems

ok, wildfly work normally.


---------------------------------------------------------------
![screenshot from 2018-03-21 18-19-55](https://user-images.githubusercontent.com/35086928/37709143-31269c74-2d44-11e8-9780-b7fb43175f5b.png)


![Uploading Screenshot from 2018-03-21  17-55-44.png…]()

**Comment by RobertCMa** [comment]
Hi @housemic, 

It's getting clear about the situation now. At first, it may need to understand that Simulator is used for the test purpose. Unlike PODM, PSME and RMM, users will modify these reference code to fit into their architecture. 

While restarting PODM service, it will proceed to discover, look for service and try to map the module to identify the service. While PODM fails to identify the service, the restart process will fail to continue binding the dependent task, like wildfly. The same situation can be seen in the practical RSD server deployment environment.

That's why it's important to understand the Rack architecture, network topology, and service type (network, storage, IO pool) before RSD service deployment, which will need to be modified in the configuration file. 

There are two logs for the reference, which can help understand the process flow.
/var/log/wildfly/console.log
/var/log/pod-manager/pod-manager-application.log

**Comment by housemic** [comment]
Dear RobertCMa,
the following is log files -

/var/log/wildfly/console.log
[console.log](https://github.com/intel/intelRSD/files/1841337/console.log)

/var/log/pod-manager/pod-manager-application.log
[pod-manager-application.log](https://github.com/intel/intelRSD/files/1841338/pod-manager-application.log)

/var/log/pod-manager/pod-manager-services-detection
[pod-manager-services-detection.log](https://github.com/intel/intelRSD/files/1841339/pod-manager-services-detection.log)

House

**Comment by RobertCMa** [comment]
Hi @housemic,

It can see from the log that the discovery failed and wildfly running into exception. Same as the real environment in my setup. As long as the ServicesConfiguration is setup correctly, the service can be restarted successfully.


2018-03-24 01:35:51,275 [ServerService Thread Pool -- 67] ERROR c.i.p.d.e.e.EventSubscriptionTask - Error while subscribing to event service for '5fd94b30-2cbc-11e8-855e-af50f2759ad3
com.intel.podm.client.WebClientRequestException: Error while getting resource from the external service

**Comment by housemic** [comment]
Dear RobertCMa,
thank you.
this is correct that
As long as the ServicesConfiguration is setup correctly, the service can be restarted successfully.


Could you help the question ? 

Question 1 - 
when I create a new PODM, wildfly is normal.
and I do not change settings in /etc/pod-manager/events.json.
the settings are original -
"ServicesConfiguration": [
{
"ServiceType": "psme",
"NetworkInterfaceName": "eth0.4094",
"PodManagerIpAddress": null
},

but when I run PSME Mock (node js simulator),
wildfly become fail,

but after I stop PSME Mock,
wildfly is still fail,

Do you have the same status ? 
thank you

-------------------------------------------------------------------

Question 2 -
I try to modify /etc/pod-manager/events.json.
change to -
"ServicesConfiguration": [
{
"ServiceType": "psme",
"NetworkInterfaceName": "lo",
"PodManagerIpAddress": null
},

and wildfly become OK.

I think the it is not normal.
Could you have comments ? 
thank you
House

**Comment by RobertCMa** [comment]
Hi @housemic,

Whenever there is change/modification of the configuration, it will be good to flush out the cache data as below.
sudo pod-manager-clean-database-immediately
and then
sudo service pod-manager restart

**Comment by housemic** [comment]
Dear RobertCMa,
when 
sudo pod-manager-clean-database-immediately
have error -
![img_0479](https://user-images.githubusercontent.com/35086928/38559483-b587ff1e-3d05-11e8-857d-5775c2dbf39f.JPG)

**Comment by RobertCMa** [comment]
Hi  @housemic,

Proceed the "pod-manager-clean-database-immediately" will restart PostgreSQL and clean out database data. Your screen log also implied the connection to the dadabase server is not successful. It will be good to check podm service status to clarify if it's running successfully.

**Comment by housemic** [comment]
Dear RobertCMa,,
I install a new PODM (No.3)  and PSME Mock,
when startup PSME Mock, 
https://localhost:8443/redfish/v1/Systems   can display HW assets.
and http://localhost:9443/redfish/v1/Systems   can display HW assets.

after stop PSME Mock, 
PODM wildfly is still alive, not found the issue : 404 - Not Found.

so the issue can be closed. thank you
House

**Comment by RobertCMa** [comment]
Good to hear that the issues are clarified. Let's conclude this.
