### ISSUE TITLE
CTS 2.1.3.32.0 installed but can't list test packages and can't execute test scripts

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#62]
Dear intel,
my detail logs are in attachment - 
[2018-05-30-CTS-2-1-Command-and-Report.zip](https://github.com/intel/intelRSD/files/2052668/2018-05-30-CTS-2-1-Command-and-Report.zip)

Question 1 -
I installed CTS 2.1.3.32.0, list test packages but found nothing when I run the command -
cts tests list

the result is in attachment - \screenshot\Screenshot-1.png

Question 2 -
CTS 2.1.3.32.0 also can't execute test scripts when I run the command -
cts execute tests Rack_Scale_2_1_PSME --config_files ./config/psme.ini

it can't generate cts_report.
the result is in attachment - \screenshot\Screenshot-2.png ~ Screenshot-4.png

my installation steps are in  attachment - \installation\

cts log in /var/log/cts/ is in  attachment - \cts_log\

House

**Comment by RobertCMa** [comment]
Hi @housemic ,

Please help check the test package permission inside the folder.  The python files (.py) should have the execute permission.  

ls -al /opt/cts/tests/Rack_Scale_2_1_PSME/required/

**Comment by tmacieje** [comment]
To mark all tests as executable please run: 
`[sudo] chmod +x /opt/cts/tests/ -R` 
and to correct ownership
`[sudo] chown user /opt/cts/tests/ -R` where _user_ is a name of the user you use to run the CTS

**Comment by housemic** [comment]
Dear RobertCMa and tmacieje,
thank you,
the question was solved,
the issue can be closed.

*.py (Python) need become executed and owner is usr instead of root.

House

**Comment by RobertCMa** [comment]
Great to hear the issue is solved. Conclude the issue and close.
