### ISSUE TITLE
CTS 2.1.3.32.0 generated CTS reports, but how to check test result ?

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#64]
Dear Intel,
the question is related to #62.

my detail logs are in attachment -
[2018-06-04-podm-cts-2-1-report.zip](https://github.com/intel/intelRSD/files/2068395/2018-06-04-podm-cts-2-1-report.zip)

Question 1 -
CTS 2.1.3.32.0 generated CTS reports, but how to check test result ?

CTS reports are in attachment - \cts_report\

**Comment by RobertCMa** [comment]
Hi @housemic,

From the podm log, it can see that the configuration file is not providing the parameter info for the test case. 

======================================
	Checking configuration	Failed
	ERROR	2018-06-04 11:33:16.205179	Required configuration parameter IsPsmePresent not defined
	ERROR	2018-06-04 11:33:16.256102	Required configuration parameter PowerEfficiency not defined
	ERROR	2018-06-04 11:33:16.306854	Required configuration parameter FanPositionNumberingConsistent not defined
	ERROR	2018-06-04 11:33:16.365813	Required configuration parameter PowerSupplyPositionNumberingConsistent not defined
	ERROR	2018-06-04 11:33:16.416771	Required configuration parameter IsRMMNetworkPrivateManagement not defined
	ERROR	2018-06-04 11:33:16.466333	Required configuration parameter AreManagementAndProductionNetworksSeparated not defined
	ERROR	2018-06-04 11:33:16.518959	Required configuration parameter AreComputeBladesServiceableIndependently not defined
======================================

It can refer to the README.pdf in RSD 2.1 CTS folder to get the detail about the parameter. Or, it's suggested to generate a sample confguration fle for test case as below:

cts tests generate_config Rack_Scale_2_1_POD_Manager hardware_check_list -o output_file_with_configuration.ini

In the sample configuration file "output_file_with_configuration.ini", it can find all the parameters.

Second, it's needed to check all the response data which is not response [200]. Manually send the command to clarify if the target supports the API or designed with its value range/limit.  

Third, scan warning and error from the log to catch all the items. Identify if there is schema or definition difference.

**Comment by housemic** [comment]
Dear RobertCMa,
I have new questions that need your support -
in attachment -
2018-06-04-podm-cts-2-1-report.zip

I run test package - Rack_Scale_2_1_PSME by the command - 
cts execute tests Rack_Scale_2_1_PSME --config_files ./config/psme.ini

and get CTS report for PSME Compute 
(cts report is in attachment - \cts_report\cts_report_3_psme.txt )

there are contents -
CTS version	2.1.3.32.0
Test run ID	 #3

Test script	/opt/cts//tests/Rack_Scale_2_1_PSME/required/crud_operations.py
Overall status	Failed
Pass rate	2/3


Question 2 -
for the item - Overall status	Failed
Why I get "Failed" Overall status	?
Are there any rule ?

Question 3 -
for the item - Pass rate	2/3
Are there rules to decide Pass or fail ?

Question 4 -
Could you have documents to describe "Overall status" and "Pass rate" ?


House

**Comment by tmacieje** [comment]
Hi @housemic 

I'll try to answer your questions. 
To get _Overall status_ PASSED, all subtest must return positive status (Positive values are: PASSED and PASSED WITH WARNINGS) 

In this case, phase _API crawling_ return Failed. 
Each Error during this process leads to the completion of this test as unsuccessful. 

Few examples:
```
	ERROR	2018-06-04 15:51:52.733535	/redfish/v1/Managers/Self#: Object of type Manager.v1_2_0.Manager; unexpected properties: [HostInterfaces]
```
or 
```
	MESSAGE	2018-06-04 15:51:48.617332	-Get https://10.3.0.2/redfish/v1/TaskService/Tasks
	ERROR	2018-06-04 15:51:48.738019	Unable to parse resource /redfish/v1/TaskService/Tasks to json due to error 'Expecting value: line 1 column 1 (char 0)'
	ERROR	2018-06-04 15:51:48.796727	Error while executing GET /redfish/v1/TaskService/Tasks
	ERROR	2018-06-04 15:51:48.849543	Unable to retrieve resource /redfish/v1/TaskService/Tasks. Empty resource received.
```

_Pass rate_ depends on the amount under the tests performed by the tool.

**Comment by housemic** [comment]
Dear tmacieje,  
thank you
House

**Comment by housemic** [comment]
Dear RobertCMa,
I run again the test package - Rack_Scale_2_1_POD_Manager and add setting file - hardware_check_list.ini.
detail result is in attachment -
[2018-06-25-podm-cts-2-1-setup-podm.zip](https://github.com/intel/intelRSD/files/2139641/2018-06-25-podm-cts-2-1-setup-podm.zip)

PODM config files is in attachment - podm.ini
PODM CTS command is in attachment - cts_command_podm.sh
PODM CTS report is in attachment - cts_report_5_podm
House

**Comment by RobertCMa** [comment]
Hello @housemic ,

With the configuration parameters, the test is ok to run. Is there questions for this or we can conclude the issue here.

**Comment by housemic** [comment]
Dear RobertCMa,
the issue can be closed, thank you.
Hoouse
