### ISSUE TITLE
Intel RSD v2.3 Pod Manager User Guide shows software version as v2.2 

### ISSUE THREAD

**Issue by phanikiranthaticharla** [intel/intelRSD#66]
The software version in Pod Manager User Guide is wrongly showing v2.2 instead of v2.3 as seen in the first page of the link below. 

https://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/podm-user-guide-v2-3.html

**Comment by RobertCMa** [comment]
Hi @phanikiranthaticharla ,

Thanks for the notification. Will feedback for the update at the next release.

**Comment by RobertCMa** [comment]
The updated PODM user guide 2.3.1 is on the Intel web site.

**Comment by phanikiranthaticharla** [comment]
Thank you! :)
