### ISSUE TITLE
About storage server, running psme-rest-server and psme-storage on different nodes

### ISSUE THREAD

**Issue by AndyCCChang** [intel/intelRSD#67]
Hi,
For the storage server (PSME-STORAGE), is it possible to run the psme-rest-server on a server and run the psme-storage on another server and connect them together? If yes, what is the configuration needs to be done?

Thank you.
AndyCCChang

**Comment by RobertCMa** [comment]
Hi @AndyCCChang,

Theoretically, it's possible as REST server adopting JSON-RPC as a transport to communicate with storage agent. Considering the security and authentication between the agent and server, Intel RSD do not make it that way and have both services stay in the same system. To make the innovation for your desired architecture, feel free to use this reference code as a basis for your own version of Intel RSD-based compliant infrastructure systems.

For the related configuration, it can start from the file/schema @ \PSME\agent\storage\configuration_schema.json.

**Comment by RobertCMa** [comment]
Hi @AndyCCChang ,

This issue will be concluded by this week if is no further activities. Thanks.
