### ISSUE TITLE
Certification questions for Intel PODM and Customized PSME

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#70]
Dear Intel ,
I install Intel PODM 2.3 and Customized PSME (not Intel PSME),
I have certification questions.

1. Intel PODM uses CA certification file - root.crt,
    and uses client certification file - client.jks.

2. Customized PSME uses CA certification file - a.pem,
    and uses client certification file - b.pem.

3. I want to do that -
    Intel PODM read Customized PSME data (PSME Computer and storage resource),

4. but Intel PODM application.log has error message - denied access,
    I think that I got certification problem.

5. Could Intel have suggestion for the certification problem ?
    for example - Can Intel PODM read pem file for client certification ?
    or Can  Intel PODM read bypass (cancel) CA and client certification ?

thank you
House

**Comment by RobertCMa** [comment]
Hi @housemic 

Security is the mandatory and required item for Intel RSD compliance. To temporarily turn off the TLS certification, it can refer to the PODM user guide chapter 4.3 for the description.

The certifiaction (.pem) file can be used by cURL, or imported into a web browser such as Firefox* or Chrome*.

Example usage with cURL:
curl -k -i --cert client.pem --cacert /var/lib/pod-manager/root.crt -X GET https://<psme_ip>:8443/redfish/v1/

While distributing the CA certificate file to RMM/PSME, it can refer to the PODM user guide chapter 4.6.4 and PSME user guide chapter 2.3.1. In the meanwhile, starting from PODM 2.3, the new feature of server certification verification is turned on by default. If this is not used, it can be turned off, like the description in PODM user guide chapter 4.4.

**Comment by RobertCMa** [comment]
Hi @housemic ,

Do we conclude this issue and follow up with others ?

**Comment by housemic** [comment]
Dear RobertCMa ,
the question can be closed, thank you
House
