### ISSUE TITLE
Schema versions not mapped properly

### ISSUE THREAD

**Issue by josue0175** [intel/intelRSD#73]
Hi Robert,

Attached you’ll find the output of the CTS run that shows the problems we’re encountering.

Problem simply stated is, “the schema versions that are used by default for CTS do not match the supported schema versions reported by our Red Fish Service.”
The failures can be seen by searching for “Failed” or “Unknown Entity Type”.
The cts MapTypes optional configuration (mapping Entity Type versions) was attempted but only 2 types were resolved and therefore only some of the failures were remedied.

Can you help us track this problem down?

**Comment by josue0175** [comment]
Attached file

[ctsfile.gz](https://github.com/intel/intelRSD/files/2210741/ctsfile.gz)

**Comment by tmacieje** [comment]
Hi @josue0175 
Can you attach a configuration file used for this test?
Also can you dump a test case report by: 
```cts status dump {{ test_number }} -o text```

I made some tests and when I add `MapTypes`

```MapTypes="Memory.v1_3_0:Memory.v1_1_0,JsonSchemaFile.v1_0_2:JsonSchemaFile.v1_0_4,Manager.v1_0_0:Manager.v1_1_0,Manager.v1_0_2:Manager.v1_1_0,Chassis.v1_0_0:Chassis.v1_4_0,Role.v1_0_0:Role.v1_2_0,SimpleStorage.v1_0_0:SimpleStorage.v1_2_0,Processor.v1_0_0:Processor.v1_1_0,EthernetInterface.v1_0_0:EthernetInterface.v1_3_0,EthernetInterface.v1_1_0:EthernetInterface.v1_3_0,EthernetInterface.v1_0_2:EthernetInterface.v1_3_0,EthernetInterface.EthernetInterface:EthernetInterface.v1_3_0"```

CTS detect all dependencies:
```
+------------------------------------------------------------------------------------------------------------------------

Test Case: SetUp

	WARNING	2018-07-20 10:17:48	CTS is configured to use the following type mappings to validate instances of 
					unknown types:
	WARNING	2018-07-20 10:17:48		- Memory.v1_3_0:Memory.v1_1_0; [#Id=f62e38093b6c0beedfbb6f3b0bd31890]
	WARNING	2018-07-20 10:17:48		- Processor.v1_0_0:Processor.v1_1_0; [#Id=8349e3dbc6be31ea1e963054af6dee69]
	WARNING	2018-07-20 10:17:48		- EthernetInterface.v1_0_0:EthernetInterface.v1_3_0; 
					[#Id=427121663cf98a9ae877eed91ad0d1de]
	WARNING	2018-07-20 10:17:48		- EthernetInterface.EthernetInterface:EthernetInterface.v1_3_0; 
					[#Id=3d2697e2017ae229d06c02840982b4e0]
	WARNING	2018-07-20 10:17:48		- SimpleStorage.v1_0_0:SimpleStorage.v1_2_0; 
					[#Id=761527fe7d152ce05d44a8aac3872011]
	WARNING	2018-07-20 10:17:48		- JsonSchemaFile.v1_0_2:JsonSchemaFile.v1_0_4; 
					[#Id=05201752599ab8a7d5cbab6775a83249]
	WARNING	2018-07-20 10:17:48		- Role.v1_0_0:Role.v1_2_0; [#Id=bacaee4bab30e93c771097fb3f720179]
	WARNING	2018-07-20 10:17:48		- Chassis.v1_0_0:Chassis.v1_4_0; [#Id=71bb3fc0d01926a50f8dbb6bd1b12d76]
	WARNING	2018-07-20 10:17:48		- Manager.v1_0_0:Manager.v1_1_0; [#Id=a6cde26e40cf52232047ea7c5b813930]
	WARNING	2018-07-20 10:17:49		- Manager.v1_0_2:Manager.v1_1_0; [#Id=0e288dcb53947b88810ba9b731a44cea]
	WARNING	2018-07-20 10:17:49		- EthernetInterface.v1_1_0:EthernetInterface.v1_3_0; 
					[#Id=ace3b8c49fa522b525a721299c2a5fb6]
	WARNING	2018-07-20 10:17:49		- EthernetInterface.v1_0_2:EthernetInterface.v1_3_0; 
					[#Id=488a5994f1beaeaeb2eaac8e67a2a98c]
	MESSAGE	2018-07-20 10:17:49	Loading metadata for services: SS_2_3, using qualifiers: SS_2_3, SS

	[[32mPassed[0m]	SetUp

+------------------------------------------------------------------------------------------------------------------------
```

**Comment by tmacieje** [comment]
@josue0175 
You should correct configuration at Map Types. 
Example
If `EthernetInterface.v1_3_0` is an unknown element for CTS, `EthernetInterface.v1_1_0` is know the type, map types field should like this:
`MapTypes=“EthernetInterface.v1_3_0:EthernetInterface.v1_1_0"`

MapTypes is a list (comma separated) of pairs T1:T2, where T1 is fully qualified type that is unknown to CTS and T2 is fully qualified type that is known to CTS. CTS will use T2 to validate instances of T1.

If in your configuration, you put more MapTypes:
`MapTypes=“EthernetInterface.v1_3_0:EthernetInterface.v1_1_0,EthernetInterface.v1_3_0:EthernetInterface.v1_0_0”`

`EthernetInterface.v1.3.0` will be mapped to `EthernetInterface.v1.0.0.` CTS override map types v1.1.0

**Comment by RobertCMa** [comment]
Close this issue as the test can proceed.
