### ISSUE TITLE
PODM 2.3 - Create Server Certificate but not found ca.pfx

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#74]
Dear Intel,
the question is related to --
Certification questions for Intel PODM and Customized PSME #70

Question 1 -
I use the command to get keystore passwword -
java -jar /usr/lib/pod-manager/vault-decrypter.jar --password-type keystore
i78eocdM3tv7dCbYaX48a1

I refer PODM 2.3 user guide to  Create Server Certificate, 
and want to keep the original CA certificate file - root.crt,
I think root.crt is an existed CA certificate file,
so refer the command -
sudo pod-manager-certificate-creation.sh --certificate-type "server" --ca-certificate-file /path//to/ca/file/ca.pfx --certificate-dname "/C=PL/ST=State/L=locality/O=organization/CN=fqdn_or_ip"

But I only find root.crt,
Where can find ca.pfx ?
or How to generate ca.pfx ?

Question 2 -
If I use root.crt to replace ca.pfx, use the command -
sudo pod-manager-certificate-creation.sh --certificate-type "server" --ca-certificate-file /var/lib/pod-manager/root.crt --certificate-dname "/C=PL/ST=State/L=locality/O=organization/CN=fqdn_or_ip"
 
the screen display -
Please provide password of CA keystore file: 

I input - "i78eocdM3tv7dCbYaX48a1"

but  got the error message -

140652942571160:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1217:
140652942571160:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=PKCS12
error: command execution failed 'openssl pkcs12 -nokeys -in /var/lib/pod-manager/root.crt -passin pass:i78eocdM3tv7dCbYaX48a1 -out /tmp/keystore/ca/root.crt'

Could you help ? thank you

House

**Comment by RobertCMa** [comment]
Hi @housemic,

To create the pfx file, it can refer to the PODM user guide chapter 4.6.2.2. The 3 examples can be a reference to create a new one, or sign with existing CA certificate. For the detail, it can check on the implementation of "pod-manager-certificate-creation.sh", which takes use of the generic linux/ubuntu tools of openssl and keytool. 

It will be helpful to turn on the verbose with adding the parameter -v. From the error message, it looks like related to the format issue. To make sure your input file format is correct, it can refer to openssl manual page for the detaiil. 

140652942571160:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=PKCS12
error: command execution failed 'openssl pkcs12 -nokeys -in /var/lib/pod-manager/root.crt -passin pass:i78eocdM3tv7dCbYaX48a1 -out /tmp/keystore/ca/root.crt'

**Comment by housemic** [comment]
Dear RobertCMa,
the question can be closed, thank you.
House

**Comment by RobertCMa** [comment]
Close per the issue was identified
