### ISSUE TITLE
PODM 2.2 - Import Client Certificate but not found ca.pfx

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#75]
Dear Intel -
the question is related to --
PODM 2.3 - Create Server Certificate but not found ca.pfx #74

Question 1 -
I use the command to get keystore passwword -
java -jar /usr/lib/pod-manager/vault-decrypter.jar --password-type keystore
i78eocdM3tv7dCbYaX48a1

I refer PODM 2.3 user guide to Import Client Certificate,
and want to keep the original CA certificate file - root.crt,
I think root.crt is an existed CA certificate file,
so refer the command -
sudo pod-manager-certificate-import.sh -c /path/to/ca/file/ca.pfx

But I only find root.crt,
Where can find ca.pfx ?
or How to generate ca.pfx ?

Question 2 -
If I use other system's client certificate file - client.pem that to replace ca.pfx, use the command -
sudo pod-manager-certificate-import.sh -c /var/lib/pod-manager/client.pem

the screen display -
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore client.jks -destkeystore client.jks -deststoretype pkcs12".
Importing keystore /var/lib/pod-manager/user.pem to client.jks...
Enter source keystore password: 

I input the keystore password- " i78eocdM3tv7dCbYaX48a1"

but I got error -

keytool error: java.io.IOException: toDerInputStream rejects tag type 45
error: command execution failed 'keytool -importkeystore -srckeystore /var/lib/pod-manager/user.pem -srcstoretype pkcs12 -keypass i78eocdM3tv7dCbYaX48a1 -storepass i78eocdM3tv7dCbYaX48a1 -destkeystore client.jks -deststoretype JKS'

Could you help ? thank you

House

**Comment by RobertCMa** [comment]
Hi @housemic ,

To create the pfx file, it can refer to the PODM user guide chapter 4.6.2.1. The 3 examples can be a reference to create a new one, or sign with existing CA certificate. For the detail, it can check on the implementation of "pod-manager-certificate-creation.sh", which takes use of the generic linux/ubuntu tools of openssl and keytool. 


To import the certificate, it's assumed that the signed certificate container used is of type PKCS #12. Please check on your certificate file format. It can take use of openssl to convert the format, which can refer to the openssl manual page for the detail operation.

**Comment by housemic** [comment]
Dear RobertCMa,
the question can be closed, thank you.
House

**Comment by RobertCMa** [comment]
Close per the issue was identified
