### ISSUE TITLE
PODM is not able to communicate with PSME

### ISSUE THREAD

**Issue by sumanchakraborty1510** [intel/intelRSD#76]
Hi ,

I am trying to bring up PSME and PODM. I am able to see the redfish services of PSME from PODM machine using wget and curl commands.

But the PODM is unable to see the PSME API's .

I am getting error as "Error while polling external service"

Attaching the log for your reference

[pod_manager_health_check_2018-07-23-16-16-05-926.tar.gz](https://github.com/intel/intelRSD/files/2219013/pod_manager_health_check_2018-07-23-16-16-05-926.tar.gz)

[psme-nvme.log](https://github.com/intel/intelRSD/files/2219018/psme-nvme.log)

[psme-rest.log](https://github.com/intel/intelRSD/files/2219019/psme-rest.log)

**Comment by RobertCMa** [comment]
Hi @sumanchakraborty1510 ,

From the log, it found the wildfly error before detect PSME and did bot see its recover for normal operation.
018-07-23 16:06:56,687 ERROR [org.jboss.as.ee] (EE-ManagedScheduledExecutorService-default-Thread-1) WFLYEE0110: Failed to run scheduled task: 

It will need to make sure pod-manager and its related services, like Wildfly, and postgresql, all work normally. Please check the service status with the command below:
"sudo service pod-manager status"


In the meanwhile, it found the version change. It will be better to clean the database to flush out the old data. It can take use of the commands below:

sudo pod-manager-clean-database-immediately
and then
sudo service pod-manager restart

**Comment by sumanchakraborty1510** [comment]
Thanks robert. It Worked
