### ISSUE TITLE
Install PODM 2.3 but Wildfly startup error

### ISSUE THREAD

**Issue by yiwong** [intel/intelRSD#80]
Dear intel,
Wildfly startup error，the issue is related to -ERROR [org.jboss.as.ee] (EE-ManagedScheduledExecutorService-default-Thread-1) WFLYEE0110: Failed to run scheduled task: java.lang.IllegalStateException: WFLYEE0111: Cannot run scheduled task com.intel.podm.services.detection.ssdp.SearchRedfishServiceTask@5133f6ce as container is suspended
the detail error message are in the following log file,
[
[console.log](https://github.com/intel/intelRSD/files/2230692/console.log)
[server.log](https://github.com/intel/intelRSD/files/2230693/server.log)

](url)

Could you help to check the issue ?
thank you

**Comment by RobertCMa** [comment]
Hi @yiwong,

You can refer to the wildfly forum https://developer.jboss.org/en/wildfly

Some similar cases may help on to resolve the container situation.

**Comment by yiwong** [comment]
hi @RobertCMa
correct answer is:
https://developer.jboss.org/message/982482#982482

We "solved" this via implementing a JMX notification listener that subscribes to the jboss.root:type=state MBean notifications (the above mentioned jboss.as:management-root=server MBean doesn't produce any notifications so we had to look for another one) and detects changes to the RunningState attribute. 

If the RunningState changes from normal to suspending we stop all the Spring message listeners ourselves - and we can also use this to stop anything else we like (like scheduling anything via ManagedScheduledExecutorService so that WFLYEE0111 don't keep occurring until the server is stopped) 

Similarly we can also detect completion of the server startup/resume by detecting the change of RunningState from suspended to normal and start all those tasks afterwards. 

Not sure if there isn't a better approach to solve this.

but I don't how to resolve it.
Could you help me to resolve it.
thank you

**Comment by RobertCMa** [comment]
Hi @yiwong ,

The forum is the key contributor to Wildfly. It's suggested to keep consulting with the experts in the forum. Believe the domain expertise will have more ideas to help on.

**Comment by yiwong** [comment]
hi @RobertCMa,
thank you

**Comment by RobertCMa** [comment]
Close the issue as it's clarified.

**Comment by lalithabheemavarapu** [comment]
Dear Intel

Currently am working on Intel RSD PODM ,

I got the  wildfly startup error

2019-04-02 02:47:31,599 ERROR [org.jboss.as.ee] (EE-ManagedScheduledExecutorService-default-Thread-1) WFLYEE0110: Failed to run scheduled task: java.lang.IllegalStateException: WFLYEE0111: Cannot run scheduled task com.intel.podm.services.detection.ssdp.SearchRedfishServiceTask@2789361a as container is suspended

Can i know how it gonna implement
