### ISSUE TITLE
Does psme-storage support kernel mode NVMeOF target?

### ISSUE THREAD

**Issue by aneeeshp3** [intel/intelRSD#83]
I am experimenting with the Storage Services & psme-storage. I see from the Storage API specification (storage-services-api-spec-v2-3.pdf) that it support NVMeOF. But the configuration file in the psme-storage agent in reference code does not have any option to specify NVMeOF target details.

Does psme-storage support NVMeOF target (kernel mode, SPDK, etc.)?
Or
Does it only work with iSCSI target?

**Comment by RobertCMa** [comment]
Hi @aneeeshp3 ,

For the NVMeof related configuration, it can refer to the \agent\nvme\configuration.json

**Comment by aneeeshp3** [comment]
Hi @RobertCMa,
Thank you. \agent\nvme\configuration.json works with psme-nvme only right? Does it work with psme-storage?

I have tried the psme-nvme, but it does not represent the NVMeOF as per Storage API specification (storage-services-api-spec-v2-3.pdf). Instead, it represents the NVMeOF using the Redfish Common Fabric Model (Section 12.8.1 in architecture-spec-v2-3.pdf).

My requirement is to represent the NVMeOF kernel mode target as a storage pool (Swordfish StorageService schema, Figure 2 in storage-services-api-spec-v2-3.pdf). Can this be done using any of the available psme components?

**Comment by RobertCMa** [comment]
Hi @aneeeshp3 ,

As the description in session 12.8 in architecture spec, NVMeOF is exposed with the Redfish Common Fabric Model. It will also need to set up the volume to associate the NVMeoF Endpoint with the StorageService, which is addressed in Figure 2 of storage-services-api-spec-v2-3.pdf.

**Comment by RobertCMa** [comment]
Hi @aneeeshp3 ,

There is no activities for 2 weeks. If there is no issue for this, will conclude by end of the week. Thanks.

**Comment by aneeeshp3** [comment]
Thank you for the support. Closing the issue since my query is answered.
