### ISSUE TITLE
Does psme-storage support NVMe drive?

### ISSUE THREAD

**Issue by AndyCCChang** [intel/intelRSD#88]
Hi,
Does psme-storage support NVMe drive? 
I would like to provide a san boot feature on the NVMe drives, does it work?
Cause when I run psme-rest and psme-storage, the SATA drive can be composed with a node as a san boot node. 
But when I add NVMe drive, the Chassis/x/Drives/x API only shows information of SATA drive but it does not show information of NVMe drives. So I was wondering if psme-storage support NVMe drive?

Thank you!

**Comment by RobertCMa** [comment]
Hi @AndyCCChang ,

Does it mean local NVMe SSD drive or NVMe over Fabric? What's the connection in this case ?

**Comment by AndyCCChang** [comment]
Hi @RobertCMa ,
It is local NVMe SSD drive.

Thank you.

**Comment by RobertCMa** [comment]
Hi @AndyCCChang ,

For local NVMe SSD drive, it's supported in Storage agent. It can refer to the spec of Storage Service API and check the related info in "Table 36. Drive Protocol Attributes". In the meanwhile, it's suggested to check on the BIOS in that system if it can identify the NVMe protocol and exposed that info in the SMBIOS. The related info can be found in RSD Firmware Extension Specification.

**Comment by AndyCCChang** [comment]
Hi @RobertCMa ,
Thank you for your reply.

Close the issue.
